[package]
name = "quill"
version = "0.2.8"
authors = ["DFINITY Team"]
edition = "2018"

[[bin]]
name = "quill"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.34"
candid = "0.7.8"
chrono = "0.4.9"
clap = "3.0.0-beta.2"
crc32fast = "1.2.0"
hex = {version = "0.4.2", features = ["serde"] }
ic-base-types = { git = "https://github.com/dfinity/ic", rev = "bd3b73e075aea1cc81b23b38ccfb138ca4ab17ab" }
ic-nns-constants = { git = "https://github.com/dfinity/ic", rev = "bd3b73e075aea1cc81b23b38ccfb138ca4ab17ab" }
ledger-canister = { git = "https://github.com/dfinity/ic", rev = "bd3b73e075aea1cc81b23b38ccfb138ca4ab17ab" }
openssl = "0.10.32"
serde = "1.0"
serde_cbor = "0.11.1"
serde_json = "1.0.57"
serde_bytes = "0.11.2"
tokio = { version = "1.2.0", features = [ "fs" ] }
ic-agent = "0.8.0"
ic-types = "0.2.2"

[features]
static-ssl = ["openssl/vendored"]

